// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_blocks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMemoryBlockVersions = `-- name: CountMemoryBlockVersions :one
SELECT COUNT(*)::int
FROM memory_blocks
WHERE user_id = $1 AND name = $2
`

type CountMemoryBlockVersionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CountMemoryBlockVersions(ctx context.Context, arg CountMemoryBlockVersionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countMemoryBlockVersions, arg.UserID, arg.Name)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countMemoryBlocksByUser = `-- name: CountMemoryBlocksByUser :one
SELECT COUNT(DISTINCT name)::int
FROM memory_blocks
WHERE user_id = $1
`

func (q *Queries) CountMemoryBlocksByUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMemoryBlocksByUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createMemoryBlock = `-- name: CreateMemoryBlock :one
INSERT INTO memory_blocks (
    user_id, name, tier, value, version, sort_order, memory_type, scope, expires_at, tags, session_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id
`

type CreateMemoryBlockParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Tier       string             `json:"tier"`
	Value      pgtype.Text        `json:"value"`
	Version    int32              `json:"version"`
	SortOrder  int32              `json:"sort_order"`
	MemoryType string             `json:"memory_type"`
	Scope      string             `json:"scope"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Tags       []string           `json:"tags"`
	SessionID  pgtype.UUID        `json:"session_id"`
}

func (q *Queries) CreateMemoryBlock(ctx context.Context, arg CreateMemoryBlockParams) (MemoryBlock, error) {
	row := q.db.QueryRow(ctx, createMemoryBlock,
		arg.UserID,
		arg.Name,
		arg.Tier,
		arg.Value,
		arg.Version,
		arg.SortOrder,
		arg.MemoryType,
		arg.Scope,
		arg.ExpiresAt,
		arg.Tags,
		arg.SessionID,
	)
	var i MemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.MemoryType,
		&i.ExpiresAt,
		&i.Scope,
		&i.IsCurrent,
		&i.Tags,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.SessionID,
	)
	return i, err
}

const deleteExpiredMemories = `-- name: DeleteExpiredMemories :exec
DELETE FROM memory_blocks
WHERE expires_at IS NOT NULL AND expires_at <= NOW()
`

// Delete memory blocks that have expired
func (q *Queries) DeleteExpiredMemories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMemories)
	return err
}

const deleteMemoryBlock = `-- name: DeleteMemoryBlock :exec
DELETE FROM memory_blocks
WHERE user_id = $1 AND name = $2
`

type DeleteMemoryBlockParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// Soft delete by marking all versions (or implement actual delete)
func (q *Queries) DeleteMemoryBlock(ctx context.Context, arg DeleteMemoryBlockParams) error {
	_, err := q.db.Exec(ctx, deleteMemoryBlock, arg.UserID, arg.Name)
	return err
}

const exportMemories = `-- name: ExportMemories :many
SELECT
    cmb.id,
    cmb.guid,
    cmb.user_id,
    u.org_id,
    cmb.name,
    cmb.tier,
    cmb.value,
    cmb.tags,
    cmb.memory_type,
    cmb.scope,
    cmb.session_id,
    cmb.created_at,
    cmb.modified_at,
    cmb.expires_at
FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE (cmb.user_id = $1 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $1) AND cmb.scope = 'org')
ORDER BY cmb.created_at DESC
`

type ExportMemoriesRow struct {
	ID         int64              `json:"id"`
	Guid       uuid.UUID          `json:"guid"`
	UserID     uuid.UUID          `json:"user_id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Name       string             `json:"name"`
	Tier       string             `json:"tier"`
	Value      pgtype.Text        `json:"value"`
	Tags       []string           `json:"tags"`
	MemoryType string             `json:"memory_type"`
	Scope      string             `json:"scope"`
	SessionID  pgtype.UUID        `json:"session_id"`
	CreatedAt  time.Time          `json:"created_at"`
	ModifiedAt time.Time          `json:"modified_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Export memories in JSONL-ready format with filtering
func (q *Queries) ExportMemories(ctx context.Context, userID uuid.UUID) ([]ExportMemoriesRow, error) {
	rows, err := q.db.Query(ctx, exportMemories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportMemoriesRow{}
	for rows.Next() {
		var i ExportMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccessibleMemoryBlocks = `-- name: GetAccessibleMemoryBlocks :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE (cmb.user_id = $1 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $1) AND cmb.scope = 'org')
ORDER BY cmb.tier, cmb.sort_order, cmb.name
`

// Get memory blocks accessible to a user (personal + org-scoped)
// Requires joining with users table to get org_id
func (q *Queries) GetAccessibleMemoryBlocks(ctx context.Context, userID uuid.UUID) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getAccessibleMemoryBlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccessibleMemoryBlocksByType = `-- name: GetAccessibleMemoryBlocksByType :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE memory_type = $2
  AND ((cmb.user_id = $1 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $1) AND cmb.scope = 'org'))
ORDER BY cmb.tier, cmb.sort_order, cmb.name
`

type GetAccessibleMemoryBlocksByTypeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	MemoryType string    `json:"memory_type"`
}

// Get accessible memory blocks filtered by type
func (q *Queries) GetAccessibleMemoryBlocksByType(ctx context.Context, arg GetAccessibleMemoryBlocksByTypeParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getAccessibleMemoryBlocksByType, arg.UserID, arg.MemoryType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCurrentMemoryBlocks = `-- name: GetAllCurrentMemoryBlocks :many
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
ORDER BY id
`

// Get all current memory blocks for reindexing
func (q *Queries) GetAllCurrentMemoryBlocks(ctx context.Context) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getAllCurrentMemoryBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCurrentMemoryBlocksWithOrg = `-- name: GetAllCurrentMemoryBlocksWithOrg :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at, u.org_id
FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
ORDER BY cmb.id
`

type GetAllCurrentMemoryBlocksWithOrgRow struct {
	ID             int64              `json:"id"`
	Guid           uuid.UUID          `json:"guid"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Tier           string             `json:"tier"`
	Value          pgtype.Text        `json:"value"`
	Tags           []string           `json:"tags"`
	Version        int32              `json:"version"`
	SortOrder      int32              `json:"sort_order"`
	MemoryType     string             `json:"memory_type"`
	Scope          string             `json:"scope"`
	SessionID      pgtype.UUID        `json:"session_id"`
	RecallCount    int32              `json:"recall_count"`
	LastRecalledAt pgtype.Timestamptz `json:"last_recalled_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	ModifiedAt     time.Time          `json:"modified_at"`
	OrgID          uuid.UUID          `json:"org_id"`
}

// Get all current memory blocks with org_id for reindexing
func (q *Queries) GetAllCurrentMemoryBlocksWithOrg(ctx context.Context) ([]GetAllCurrentMemoryBlocksWithOrgRow, error) {
	rows, err := q.db.Query(ctx, getAllCurrentMemoryBlocksWithOrg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCurrentMemoryBlocksWithOrgRow{}
	for rows.Next() {
		var i GetAllCurrentMemoryBlocksWithOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentMemoryBlockByName = `-- name: GetCurrentMemoryBlockByName :one
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
WHERE user_id = $1 AND name = $2
`

type GetCurrentMemoryBlockByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetCurrentMemoryBlockByName(ctx context.Context, arg GetCurrentMemoryBlockByNameParams) (CurrentMemoryBlock, error) {
	row := q.db.QueryRow(ctx, getCurrentMemoryBlockByName, arg.UserID, arg.Name)
	var i CurrentMemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Tags,
		&i.Version,
		&i.SortOrder,
		&i.MemoryType,
		&i.Scope,
		&i.SessionID,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getCurrentMemoryBlocks = `-- name: GetCurrentMemoryBlocks :many
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
WHERE user_id = $1
ORDER BY tier, sort_order, name
`

func (q *Queries) GetCurrentMemoryBlocks(ctx context.Context, userID uuid.UUID) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getCurrentMemoryBlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentMemoryBlocksByTier = `-- name: GetCurrentMemoryBlocksByTier :many
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
WHERE user_id = $1 AND tier = $2
ORDER BY sort_order, name
`

type GetCurrentMemoryBlocksByTierParams struct {
	UserID uuid.UUID `json:"user_id"`
	Tier   string    `json:"tier"`
}

func (q *Queries) GetCurrentMemoryBlocksByTier(ctx context.Context, arg GetCurrentMemoryBlocksByTierParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getCurrentMemoryBlocksByTier, arg.UserID, arg.Tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentMemoryBlocksByType = `-- name: GetCurrentMemoryBlocksByType :many
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
WHERE user_id = $1 AND memory_type = $2
ORDER BY tier, sort_order, name
`

type GetCurrentMemoryBlocksByTypeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	MemoryType string    `json:"memory_type"`
}

func (q *Queries) GetCurrentMemoryBlocksByType(ctx context.Context, arg GetCurrentMemoryBlocksByTypeParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getCurrentMemoryBlocksByType, arg.UserID, arg.MemoryType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryBlockByGUID = `-- name: GetMemoryBlockByGUID :one
SELECT id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id FROM memory_blocks
WHERE guid = $1 AND user_id = $2
`

type GetMemoryBlockByGUIDParams struct {
	Guid   uuid.UUID `json:"guid"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemoryBlockByGUID(ctx context.Context, arg GetMemoryBlockByGUIDParams) (MemoryBlock, error) {
	row := q.db.QueryRow(ctx, getMemoryBlockByGUID, arg.Guid, arg.UserID)
	var i MemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.MemoryType,
		&i.ExpiresAt,
		&i.Scope,
		&i.IsCurrent,
		&i.Tags,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.SessionID,
	)
	return i, err
}

const getMemoryBlockByID = `-- name: GetMemoryBlockByID :one
SELECT id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id FROM memory_blocks
WHERE id = $1 AND user_id = $2
`

type GetMemoryBlockByIDParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemoryBlockByID(ctx context.Context, arg GetMemoryBlockByIDParams) (MemoryBlock, error) {
	row := q.db.QueryRow(ctx, getMemoryBlockByID, arg.ID, arg.UserID)
	var i MemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.MemoryType,
		&i.ExpiresAt,
		&i.Scope,
		&i.IsCurrent,
		&i.Tags,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.SessionID,
	)
	return i, err
}

const getMemoryBlockHistory = `-- name: GetMemoryBlockHistory :many
SELECT id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id FROM memory_blocks
WHERE user_id = $1 AND name = $2
ORDER BY version DESC
LIMIT $3 OFFSET $4
`

type GetMemoryBlockHistoryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetMemoryBlockHistory(ctx context.Context, arg GetMemoryBlockHistoryParams) ([]MemoryBlock, error) {
	rows, err := q.db.Query(ctx, getMemoryBlockHistory,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryBlock{}
	for rows.Next() {
		var i MemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Version,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.MemoryType,
			&i.ExpiresAt,
			&i.Scope,
			&i.IsCurrent,
			&i.Tags,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryContext = `-- name: GetMemoryContext :many
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
WHERE user_id = $1
ORDER BY
    CASE tier
        WHEN 'core' THEN 1
        WHEN 'index' THEN 2
        WHEN 'state' THEN 3
    END,
    sort_order,
    name
`

// Get all current memory blocks for context loading
func (q *Queries) GetMemoryContext(ctx context.Context, userID uuid.UUID) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getMemoryContext, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryScopeDistribution = `-- name: GetMemoryScopeDistribution :many
SELECT
    scope,
    COUNT(*)::bigint AS count
FROM current_memory_blocks
WHERE scope IS NOT NULL
GROUP BY scope
ORDER BY count DESC
`

type GetMemoryScopeDistributionRow struct {
	Scope string `json:"scope"`
	Count int64  `json:"count"`
}

// Get count of memories by scope for visualization
func (q *Queries) GetMemoryScopeDistribution(ctx context.Context) ([]GetMemoryScopeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getMemoryScopeDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemoryScopeDistributionRow{}
	for rows.Next() {
		var i GetMemoryScopeDistributionRow
		if err := rows.Scan(&i.Scope, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryStats = `-- name: GetMemoryStats :one
SELECT
    COUNT(DISTINCT user_id)::bigint AS users_with_memories,
    COUNT(*)::bigint AS total_memory_blocks,
    COALESCE(SUM(LENGTH(value)), 0)::bigint AS total_content_bytes,
    COUNT(DISTINCT name)::bigint AS unique_memory_names
FROM current_memory_blocks
`

type GetMemoryStatsRow struct {
	UsersWithMemories int64 `json:"users_with_memories"`
	TotalMemoryBlocks int64 `json:"total_memory_blocks"`
	TotalContentBytes int64 `json:"total_content_bytes"`
	UniqueMemoryNames int64 `json:"unique_memory_names"`
}

// Get aggregate memory statistics across all users
func (q *Queries) GetMemoryStats(ctx context.Context) (GetMemoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getMemoryStats)
	var i GetMemoryStatsRow
	err := row.Scan(
		&i.UsersWithMemories,
		&i.TotalMemoryBlocks,
		&i.TotalContentBytes,
		&i.UniqueMemoryNames,
	)
	return i, err
}

const getMemoryTypeDistribution = `-- name: GetMemoryTypeDistribution :many
SELECT
    memory_type,
    COUNT(*)::bigint AS count
FROM current_memory_blocks
WHERE memory_type IS NOT NULL
GROUP BY memory_type
ORDER BY count DESC
`

type GetMemoryTypeDistributionRow struct {
	MemoryType string `json:"memory_type"`
	Count      int64  `json:"count"`
}

// Get count of memories by type for visualization
func (q *Queries) GetMemoryTypeDistribution(ctx context.Context) ([]GetMemoryTypeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getMemoryTypeDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemoryTypeDistributionRow{}
	for rows.Next() {
		var i GetMemoryTypeDistributionRow
		if err := rows.Scan(&i.MemoryType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextMemoryBlockVersion = `-- name: GetNextMemoryBlockVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM memory_blocks
WHERE user_id = $1 AND name = $2
`

type GetNextMemoryBlockVersionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetNextMemoryBlockVersion(ctx context.Context, arg GetNextMemoryBlockVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextMemoryBlockVersion, arg.UserID, arg.Name)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const getSessionMemories = `-- name: GetSessionMemories :many
SELECT id, guid, user_id, name, tier, value, tags, version, sort_order, memory_type, scope, session_id, recall_count, last_recalled_at, expires_at, created_at, modified_at FROM current_memory_blocks
WHERE user_id = $1
  AND session_id = $2
ORDER BY created_at
`

type GetSessionMemoriesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

// Get all current memories for a specific session.
// Security: filtered by user_id — users can only see their own memories.
func (q *Queries) GetSessionMemories(ctx context.Context, arg GetSessionMemoriesParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, getSessionMemories, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTags = `-- name: GetTopTags :many
SELECT
    tag,
    COUNT(*)::bigint AS count
FROM (
    SELECT DISTINCT
        user_id,
        name,
        unnest(tags) AS tag
    FROM current_memory_blocks
    WHERE array_length(tags, 1) > 0
) AS tags_extracted
WHERE tag != ''
GROUP BY tag
ORDER BY count DESC
LIMIT $1
`

type GetTopTagsRow struct {
	Tag   interface{} `json:"tag"`
	Count int64       `json:"count"`
}

// Get most frequently used tags across all memories
func (q *Queries) GetTopTags(ctx context.Context, limit int32) ([]GetTopTagsRow, error) {
	rows, err := q.db.Query(ctx, getTopTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopTagsRow{}
	for rows.Next() {
		var i GetTopTagsRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementRecallCount = `-- name: IncrementRecallCount :exec
UPDATE memory_blocks
SET recall_count = recall_count + 1,
    last_recalled_at = NOW(),
    modified_at = NOW()
WHERE id = ANY($1::bigint[])
  AND user_id = $2
  AND is_current = true
`

type IncrementRecallCountParams struct {
	BlockIds []int64   `json:"block_ids"`
	UserID   uuid.UUID `json:"user_id"`
}

// Batch-increment recall counts for memories returned in a search.
// The user_id filter is defense-in-depth: block IDs are already derived
// from ownership-filtered search results.
func (q *Queries) IncrementRecallCount(ctx context.Context, arg IncrementRecallCountParams) error {
	_, err := q.db.Exec(ctx, incrementRecallCount, arg.BlockIds, arg.UserID)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    session_id,
    COUNT(DISTINCT name)::int AS memory_count,
    MIN(created_at)::timestamptz AS first_activity,
    MAX(created_at)::timestamptz AS last_activity
FROM current_memory_blocks
WHERE user_id = $1
  AND session_id IS NOT NULL
GROUP BY session_id
ORDER BY last_activity DESC
LIMIT $2
`

type ListUserSessionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

type ListUserSessionsRow struct {
	SessionID     pgtype.UUID `json:"session_id"`
	MemoryCount   int32       `json:"memory_count"`
	FirstActivity time.Time   `json:"first_activity"`
	LastActivity  time.Time   `json:"last_activity"`
}

// List sessions that created memories, aggregated from memory_blocks.
// Returns session_id, memory count, and time range for each session.
// Security: filtered by user_id — users can only see their own sessions.
func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.MemoryCount,
			&i.FirstActivity,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOldVersions = `-- name: PruneOldVersions :exec
DELETE FROM memory_blocks
WHERE is_current = false
  AND id NOT IN (
    SELECT id FROM memory_blocks
    ORDER BY user_id, name, version DESC
    LIMIT 1000000
  )
  AND version < (
    SELECT MIN(version) FROM (
      SELECT version FROM memory_blocks mb2
      WHERE mb2.user_id = memory_blocks.user_id
        AND mb2.name = memory_blocks.name
      ORDER BY version DESC
      LIMIT $1
    ) keep_versions
  )
`

// Delete old versions of memory blocks, keeping the most recent N versions per (user_id, name).
// The is_current row is always preserved regardless of the retention limit.
// Uses a subquery with window function to identify rows beyond the retention limit.
func (q *Queries) PruneOldVersions(ctx context.Context, limit int32) error {
	_, err := q.db.Exec(ctx, pruneOldVersions, limit)
	return err
}

const searchAccessibleMemoryBlocks = `-- name: SearchAccessibleMemoryBlocks :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE ((cmb.user_id = $1 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $1) AND cmb.scope = 'org'))
  AND (
    cmb.name ILIKE '%' || $2 || '%'
    OR to_tsvector('english', COALESCE(cmb.value, '')) @@ plainto_tsquery('english', $2)
  )
ORDER BY
    CASE WHEN cmb.name ILIKE '%' || $2 || '%' THEN 0 ELSE 1 END,
    cmb.tier, cmb.sort_order, cmb.name
LIMIT $3
`

type SearchAccessibleMemoryBlocksParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Query       pgtype.Text `json:"query"`
	SearchLimit int32       `json:"search_limit"`
}

// Search accessible memory blocks by keyword using ILIKE (name) and full-text search (value).
func (q *Queries) SearchAccessibleMemoryBlocks(ctx context.Context, arg SearchAccessibleMemoryBlocksParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, searchAccessibleMemoryBlocks, arg.UserID, arg.Query, arg.SearchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccessibleMemoryBlocksByTags = `-- name: SearchAccessibleMemoryBlocksByTags :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE ((cmb.user_id = $1 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $1) AND cmb.scope = 'org'))
  AND cmb.tags @> $2::text[]
  AND (
    cmb.name ILIKE '%' || $3 || '%'
    OR to_tsvector('english', COALESCE(cmb.value, '')) @@ plainto_tsquery('english', $3)
  )
ORDER BY
    CASE WHEN cmb.name ILIKE '%' || $3 || '%' THEN 0 ELSE 1 END,
    cmb.tier, cmb.sort_order, cmb.name
LIMIT $4
`

type SearchAccessibleMemoryBlocksByTagsParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	FilterTags  []string    `json:"filter_tags"`
	Query       pgtype.Text `json:"query"`
	SearchLimit int32       `json:"search_limit"`
}

// Search accessible memory blocks by keyword filtered by tags (AND logic).
func (q *Queries) SearchAccessibleMemoryBlocksByTags(ctx context.Context, arg SearchAccessibleMemoryBlocksByTagsParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, searchAccessibleMemoryBlocksByTags,
		arg.UserID,
		arg.FilterTags,
		arg.Query,
		arg.SearchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccessibleMemoryBlocksByType = `-- name: SearchAccessibleMemoryBlocksByType :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE memory_type = $1
  AND ((cmb.user_id = $2 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $2) AND cmb.scope = 'org'))
  AND (
    cmb.name ILIKE '%' || $3 || '%'
    OR to_tsvector('english', COALESCE(cmb.value, '')) @@ plainto_tsquery('english', $3)
  )
ORDER BY
    CASE WHEN cmb.name ILIKE '%' || $3 || '%' THEN 0 ELSE 1 END,
    cmb.tier, cmb.sort_order, cmb.name
LIMIT $4
`

type SearchAccessibleMemoryBlocksByTypeParams struct {
	MemoryType  string      `json:"memory_type"`
	UserID      uuid.UUID   `json:"user_id"`
	Query       pgtype.Text `json:"query"`
	SearchLimit int32       `json:"search_limit"`
}

// Search accessible memory blocks by keyword filtered by memory type.
func (q *Queries) SearchAccessibleMemoryBlocksByType(ctx context.Context, arg SearchAccessibleMemoryBlocksByTypeParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, searchAccessibleMemoryBlocksByType,
		arg.MemoryType,
		arg.UserID,
		arg.Query,
		arg.SearchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccessibleMemoryBlocksByTypeAndTags = `-- name: SearchAccessibleMemoryBlocksByTypeAndTags :many
SELECT cmb.id, cmb.guid, cmb.user_id, cmb.name, cmb.tier, cmb.value, cmb.tags, cmb.version, cmb.sort_order, cmb.memory_type, cmb.scope, cmb.session_id, cmb.recall_count, cmb.last_recalled_at, cmb.expires_at, cmb.created_at, cmb.modified_at FROM current_memory_blocks cmb
JOIN users u ON cmb.user_id = u.id
WHERE memory_type = $1
  AND cmb.tags @> $2::text[]
  AND ((cmb.user_id = $3 AND cmb.scope = 'personal')
   OR (u.org_id = (SELECT org_id FROM users WHERE id = $3) AND cmb.scope = 'org'))
  AND (
    cmb.name ILIKE '%' || $4 || '%'
    OR to_tsvector('english', COALESCE(cmb.value, '')) @@ plainto_tsquery('english', $4)
  )
ORDER BY
    CASE WHEN cmb.name ILIKE '%' || $4 || '%' THEN 0 ELSE 1 END,
    cmb.tier, cmb.sort_order, cmb.name
LIMIT $5
`

type SearchAccessibleMemoryBlocksByTypeAndTagsParams struct {
	MemoryType  string      `json:"memory_type"`
	FilterTags  []string    `json:"filter_tags"`
	UserID      uuid.UUID   `json:"user_id"`
	Query       pgtype.Text `json:"query"`
	SearchLimit int32       `json:"search_limit"`
}

// Search accessible memory blocks by keyword filtered by memory type and tags.
func (q *Queries) SearchAccessibleMemoryBlocksByTypeAndTags(ctx context.Context, arg SearchAccessibleMemoryBlocksByTypeAndTagsParams) ([]CurrentMemoryBlock, error) {
	rows, err := q.db.Query(ctx, searchAccessibleMemoryBlocksByTypeAndTags,
		arg.MemoryType,
		arg.FilterTags,
		arg.UserID,
		arg.Query,
		arg.SearchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentMemoryBlock{}
	for rows.Next() {
		var i CurrentMemoryBlock
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.Name,
			&i.Tier,
			&i.Value,
			&i.Tags,
			&i.Version,
			&i.SortOrder,
			&i.MemoryType,
			&i.Scope,
			&i.SessionID,
			&i.RecallCount,
			&i.LastRecalledAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemoryBlock = `-- name: UpdateMemoryBlock :one
INSERT INTO memory_blocks (
    user_id, name, tier, value, version, sort_order, memory_type, scope, expires_at, tags, session_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id
`

type UpdateMemoryBlockParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Tier       string             `json:"tier"`
	Value      pgtype.Text        `json:"value"`
	Version    int32              `json:"version"`
	SortOrder  int32              `json:"sort_order"`
	MemoryType string             `json:"memory_type"`
	Scope      string             `json:"scope"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Tags       []string           `json:"tags"`
	SessionID  pgtype.UUID        `json:"session_id"`
}

// Updates by creating a new version (version must be provided)
func (q *Queries) UpdateMemoryBlock(ctx context.Context, arg UpdateMemoryBlockParams) (MemoryBlock, error) {
	row := q.db.QueryRow(ctx, updateMemoryBlock,
		arg.UserID,
		arg.Name,
		arg.Tier,
		arg.Value,
		arg.Version,
		arg.SortOrder,
		arg.MemoryType,
		arg.Scope,
		arg.ExpiresAt,
		arg.Tags,
		arg.SessionID,
	)
	var i MemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.MemoryType,
		&i.ExpiresAt,
		&i.Scope,
		&i.IsCurrent,
		&i.Tags,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.SessionID,
	)
	return i, err
}

const updateMemoryBlockScope = `-- name: UpdateMemoryBlockScope :one
UPDATE memory_blocks
SET scope = $3,
    modified_at = NOW()
WHERE id = (
    SELECT cmb.id FROM current_memory_blocks cmb
    WHERE cmb.user_id = $1 AND cmb.name = $2
)
RETURNING id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id
`

type UpdateMemoryBlockScopeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Scope  string    `json:"scope"`
}

// Update the scope of a memory block
func (q *Queries) UpdateMemoryBlockScope(ctx context.Context, arg UpdateMemoryBlockScopeParams) (MemoryBlock, error) {
	row := q.db.QueryRow(ctx, updateMemoryBlockScope, arg.UserID, arg.Name, arg.Scope)
	var i MemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.MemoryType,
		&i.ExpiresAt,
		&i.Scope,
		&i.IsCurrent,
		&i.Tags,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.SessionID,
	)
	return i, err
}

const updateMemoryBlockType = `-- name: UpdateMemoryBlockType :one
UPDATE memory_blocks
SET memory_type = $3,
    expires_at = $4,
    modified_at = NOW()
WHERE id = (
    SELECT cmb.id FROM current_memory_blocks cmb
    WHERE cmb.user_id = $1 AND cmb.name = $2
)
RETURNING id, guid, user_id, name, tier, value, version, sort_order, created_at, modified_at, memory_type, expires_at, scope, is_current, tags, recall_count, last_recalled_at, session_id
`

type UpdateMemoryBlockTypeParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	MemoryType string             `json:"memory_type"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Update the memory type of the latest version of a memory block
func (q *Queries) UpdateMemoryBlockType(ctx context.Context, arg UpdateMemoryBlockTypeParams) (MemoryBlock, error) {
	row := q.db.QueryRow(ctx, updateMemoryBlockType,
		arg.UserID,
		arg.Name,
		arg.MemoryType,
		arg.ExpiresAt,
	)
	var i MemoryBlock
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.Name,
		&i.Tier,
		&i.Value,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.MemoryType,
		&i.ExpiresAt,
		&i.Scope,
		&i.IsCurrent,
		&i.Tags,
		&i.RecallCount,
		&i.LastRecalledAt,
		&i.SessionID,
	)
	return i, err
}
