// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       string             `json:"name"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type AuditLog struct {
	ID           int64       `json:"id"`
	Guid         uuid.UUID   `json:"guid"`
	UserID       pgtype.UUID `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Details      []byte      `json:"details"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	CreatedAt    time.Time   `json:"created_at"`
}

type CurrentMemoryBlock struct {
	ID         int64              `json:"id"`
	Guid       uuid.UUID          `json:"guid"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Tier       string             `json:"tier"`
	Value      pgtype.Text        `json:"value"`
	Tags       []string           `json:"tags"`
	Version    int32              `json:"version"`
	SortOrder  int32              `json:"sort_order"`
	MemoryType string             `json:"memory_type"`
	Scope      string             `json:"scope"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
	ModifiedAt time.Time          `json:"modified_at"`
}

type GitCommit struct {
	ID            int64       `json:"id"`
	Guid          uuid.UUID   `json:"guid"`
	UserID        uuid.UUID   `json:"user_id"`
	CommitHash    string      `json:"commit_hash"`
	CommitMessage string      `json:"commit_message"`
	AuthorName    pgtype.Text `json:"author_name"`
	AuthorEmail   pgtype.Text `json:"author_email"`
	CommittedAt   time.Time   `json:"committed_at"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Journal struct {
	ID           int64       `json:"id"`
	Guid         uuid.UUID   `json:"guid"`
	UserID       uuid.UUID   `json:"user_id"`
	EntryType    string      `json:"entry_type"`
	Content      string      `json:"content"`
	Metadata     []byte      `json:"metadata"`
	VectorID     pgtype.UUID `json:"vector_id"`
	SupersededBy pgtype.UUID `json:"superseded_by"`
	CreatedAt    time.Time   `json:"created_at"`
	ModifiedAt   time.Time   `json:"modified_at"`
}

type MemoryBlock struct {
	ID         int64       `json:"id"`
	Guid       uuid.UUID   `json:"guid"`
	UserID     uuid.UUID   `json:"user_id"`
	Name       string      `json:"name"`
	Tier       string      `json:"tier"`
	Value      pgtype.Text `json:"value"`
	Version    int32       `json:"version"`
	SortOrder  int32       `json:"sort_order"`
	CreatedAt  time.Time   `json:"created_at"`
	ModifiedAt time.Time   `json:"modified_at"`
	// Type of memory: factual (standards, policies), experiential (solutions, lessons learned), working (session context)
	MemoryType string `json:"memory_type"`
	// Optional expiration timestamp for working memories (auto-set to 7 days for working type)
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Memory visibility scope: personal (only creator sees it) or org (all users in organization see it)
	Scope     string   `json:"scope"`
	IsCurrent bool     `json:"is_current"`
	Tags      []string `json:"tags"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	Email         pgtype.Text        `json:"email"`
	DisplayName   pgtype.Text        `json:"display_name"`
	CreatedAt     time.Time          `json:"created_at"`
	ModifiedAt    time.Time          `json:"modified_at"`
	Metadata      []byte             `json:"metadata"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	IsAdmin       bool               `json:"is_admin"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	// Organization identifier - all users with same org_id can share org-scoped memories
	OrgID uuid.UUID `json:"org_id"`
}
