// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanupExpiredAdminSessions(ctx context.Context) error
	CountActiveAPIKeysByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountActiveAdminSessions(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountGitCommits(ctx context.Context, userID uuid.UUID) (int32, error)
	CountJournalEntriesByType(ctx context.Context, arg CountJournalEntriesByTypeParams) (int32, error)
	CountMemoryBlockVersions(ctx context.Context, arg CountMemoryBlockVersionsParams) (int32, error)
	CountMemoryBlocksByUser(ctx context.Context, userID uuid.UUID) (int32, error)
	CountUsers(ctx context.Context) (CountUsersRow, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateGitCommit(ctx context.Context, arg CreateGitCommitParams) (GitCommit, error)
	CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (Journal, error)
	CreateMemoryBlock(ctx context.Context, arg CreateMemoryBlockParams) (MemoryBlock, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	// Delete memory blocks that have expired
	DeleteExpiredMemories(ctx context.Context) error
	DeleteJournalEntry(ctx context.Context, arg DeleteJournalEntryParams) error
	// Soft delete by marking all versions (or implement actual delete)
	DeleteMemoryBlock(ctx context.Context, arg DeleteMemoryBlockParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Export memories in JSONL-ready format with filtering
	ExportMemories(ctx context.Context, userID uuid.UUID) ([]ExportMemoriesRow, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error)
	// Get memory blocks accessible to a user (personal + org-scoped)
	// Requires joining with users table to get org_id
	GetAccessibleMemoryBlocks(ctx context.Context, userID uuid.UUID) ([]CurrentMemoryBlock, error)
	// Get accessible memory blocks filtered by type
	GetAccessibleMemoryBlocksByType(ctx context.Context, arg GetAccessibleMemoryBlocksByTypeParams) ([]CurrentMemoryBlock, error)
	// Note: Despite the name, this query is used for all user sessions (admin and non-admin)
	GetAdminSessionByToken(ctx context.Context, tokenHash string) (GetAdminSessionByTokenRow, error)
	GetAdminStats(ctx context.Context) (GetAdminStatsRow, error)
	// Get all current memory blocks for reindexing
	GetAllCurrentMemoryBlocks(ctx context.Context) ([]CurrentMemoryBlock, error)
	// Get all current memory blocks with org_id for reindexing
	GetAllCurrentMemoryBlocksWithOrg(ctx context.Context) ([]GetAllCurrentMemoryBlocksWithOrgRow, error)
	GetAuditLogsByResource(ctx context.Context, arg GetAuditLogsByResourceParams) ([]AuditLog, error)
	GetCurrentMemoryBlockByName(ctx context.Context, arg GetCurrentMemoryBlockByNameParams) (CurrentMemoryBlock, error)
	GetCurrentMemoryBlocks(ctx context.Context, userID uuid.UUID) ([]CurrentMemoryBlock, error)
	GetCurrentMemoryBlocksByTier(ctx context.Context, arg GetCurrentMemoryBlocksByTierParams) ([]CurrentMemoryBlock, error)
	GetCurrentMemoryBlocksByType(ctx context.Context, arg GetCurrentMemoryBlocksByTypeParams) ([]CurrentMemoryBlock, error)
	GetGitCommit(ctx context.Context, arg GetGitCommitParams) (GitCommit, error)
	GetGitCommitByHash(ctx context.Context, arg GetGitCommitByHashParams) (GitCommit, error)
	GetJournalEntriesByType(ctx context.Context, arg GetJournalEntriesByTypeParams) ([]Journal, error)
	GetJournalEntriesByVectorIDs(ctx context.Context, arg GetJournalEntriesByVectorIDsParams) ([]Journal, error)
	GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (Journal, error)
	GetJournalEntryByID(ctx context.Context, arg GetJournalEntryByIDParams) (Journal, error)
	GetLatestGitCommit(ctx context.Context, userID uuid.UUID) (GitCommit, error)
	GetMemoryBlockByGUID(ctx context.Context, arg GetMemoryBlockByGUIDParams) (MemoryBlock, error)
	GetMemoryBlockByID(ctx context.Context, arg GetMemoryBlockByIDParams) (MemoryBlock, error)
	GetMemoryBlockHistory(ctx context.Context, arg GetMemoryBlockHistoryParams) ([]MemoryBlock, error)
	// Get all current memory blocks for context loading
	GetMemoryContext(ctx context.Context, userID uuid.UUID) ([]CurrentMemoryBlock, error)
	// Get count of memories by scope for visualization
	GetMemoryScopeDistribution(ctx context.Context) ([]GetMemoryScopeDistributionRow, error)
	// Get aggregate memory statistics across all users
	GetMemoryStats(ctx context.Context) (GetMemoryStatsRow, error)
	// Get count of memories by type for visualization
	GetMemoryTypeDistribution(ctx context.Context) ([]GetMemoryTypeDistributionRow, error)
	GetNextMemoryBlockVersion(ctx context.Context, arg GetNextMemoryBlockVersionParams) (int32, error)
	GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (User, error)
	GetRecentDecisions(ctx context.Context, arg GetRecentDecisionsParams) ([]Journal, error)
	GetRecentSolutions(ctx context.Context, arg GetRecentSolutionsParams) ([]Journal, error)
	// Get all current memories for a specific session.
	// Security: filtered by user_id — users can only see their own memories.
	GetSessionMemories(ctx context.Context, arg GetSessionMemoriesParams) ([]CurrentMemoryBlock, error)
	// Get most frequently used tags across all memories
	GetTopTags(ctx context.Context, limit int32) ([]GetTopTagsRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// ============================================================================
	// Admin-related queries
	// ============================================================================
	GetUserByUsernameForAuth(ctx context.Context, username string) (User, error)
	// Batch-increment recall counts for memories returned in a search.
	// The user_id filter is defense-in-depth: block IDs are already derived
	// from ownership-filtered search results.
	IncrementRecallCount(ctx context.Context, arg IncrementRecallCountParams) error
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysByUserRow, error)
	ListActiveAdminSessions(ctx context.Context) ([]ListActiveAdminSessionsRow, error)
	ListAllAPIKeys(ctx context.Context, arg ListAllAPIKeysParams) ([]ListAllAPIKeysRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListGitCommits(ctx context.Context, arg ListGitCommitsParams) ([]GitCommit, error)
	ListGitCommitsByDateRange(ctx context.Context, arg ListGitCommitsByDateRangeParams) ([]GitCommit, error)
	ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]Journal, error)
	ListJournalEntriesByDateRange(ctx context.Context, arg ListJournalEntriesByDateRangeParams) ([]Journal, error)
	// List sessions that created memories, aggregated from memory_blocks.
	// Returns session_id, memory count, and time range for each session.
	// Security: filtered by user_id — users can only see their own sessions.
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error)
	// Delete old versions of memory blocks, keeping the most recent N versions per (user_id, name).
	// The is_current row is always preserved regardless of the retention limit.
	// Uses a subquery with window function to identify rows beyond the retention limit.
	PruneOldVersions(ctx context.Context, limit int32) error
	ReactivateUser(ctx context.Context, id uuid.UUID) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
	RevokeAdminSession(ctx context.Context, id uuid.UUID) error
	RevokeAdminSessionByToken(ctx context.Context, tokenHash string) error
	RevokeAllAPIKeysByUser(ctx context.Context, userID uuid.UUID) error
	RevokeAllAdminSessionsByUser(ctx context.Context, userID uuid.UUID) error
	// Search accessible memory blocks by keyword using ILIKE (name) and full-text search (value).
	SearchAccessibleMemoryBlocks(ctx context.Context, arg SearchAccessibleMemoryBlocksParams) ([]CurrentMemoryBlock, error)
	// Search accessible memory blocks by keyword filtered by tags (AND logic).
	SearchAccessibleMemoryBlocksByTags(ctx context.Context, arg SearchAccessibleMemoryBlocksByTagsParams) ([]CurrentMemoryBlock, error)
	// Search accessible memory blocks by keyword filtered by memory type.
	SearchAccessibleMemoryBlocksByType(ctx context.Context, arg SearchAccessibleMemoryBlocksByTypeParams) ([]CurrentMemoryBlock, error)
	// Search accessible memory blocks by keyword filtered by memory type and tags.
	SearchAccessibleMemoryBlocksByTypeAndTags(ctx context.Context, arg SearchAccessibleMemoryBlocksByTypeAndTagsParams) ([]CurrentMemoryBlock, error)
	SearchJournalFullText(ctx context.Context, arg SearchJournalFullTextParams) ([]SearchJournalFullTextRow, error)
	SetJournalVectorID(ctx context.Context, arg SetJournalVectorIDParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SupersedeJournalEntry(ctx context.Context, arg SupersedeJournalEntryParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (Journal, error)
	// Updates by creating a new version (version must be provided)
	UpdateMemoryBlock(ctx context.Context, arg UpdateMemoryBlockParams) (MemoryBlock, error)
	// Update the scope of a memory block
	UpdateMemoryBlockScope(ctx context.Context, arg UpdateMemoryBlockScopeParams) (MemoryBlock, error)
	// Update the memory type of the latest version of a memory block
	UpdateMemoryBlockType(ctx context.Context, arg UpdateMemoryBlockTypeParams) (MemoryBlock, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error)
}

var _ Querier = (*Queries)(nil)
