// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE deactivated_at IS NULL) as active,
    COUNT(*) FILTER (WHERE is_admin = TRUE AND deactivated_at IS NULL) as admins
FROM users
`

type CountUsersRow struct {
	Total  int64 `json:"total"`
	Active int64 `json:"active"`
	Admins int64 `json:"admins"`
}

func (q *Queries) CountUsers(ctx context.Context) (CountUsersRow, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var i CountUsersRow
	err := row.Scan(&i.Total, &i.Active, &i.Admins)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, display_name, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id
`

type CreateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (id, username, email, display_name, password_hash, is_admin, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	DisplayName  pgtype.Text `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
	IsAdmin      bool        `json:"is_admin"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET deactivated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT
    (SELECT COUNT(*) FROM users WHERE deactivated_at IS NULL) as active_users,
    (SELECT COUNT(*) FROM users WHERE is_admin = TRUE AND deactivated_at IS NULL) as admin_users,
    (SELECT COUNT(*) FROM api_keys WHERE revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())) as active_api_keys,
    (SELECT COUNT(*) FROM admin_sessions WHERE revoked_at IS NULL AND expires_at > NOW()) as active_sessions
`

type GetAdminStatsRow struct {
	ActiveUsers    int64 `json:"active_users"`
	AdminUsers     int64 `json:"admin_users"`
	ActiveApiKeys  int64 `json:"active_api_keys"`
	ActiveSessions int64 `json:"active_sessions"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.AdminUsers,
		&i.ActiveApiKeys,
		&i.ActiveSessions,
	)
	return i, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (id, username, email, display_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET email = COALESCE(EXCLUDED.email, users.email),
    display_name = COALESCE(EXCLUDED.display_name, users.display_name)
RETURNING id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id
`

type GetOrCreateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getOrCreateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const getUserByUsernameForAuth = `-- name: GetUserByUsernameForAuth :one

SELECT id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id FROM users
WHERE username = $1 AND deactivated_at IS NULL
`

// ============================================================================
// Admin-related queries
// ============================================================================
func (q *Queries) GetUserByUsernameForAuth(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameForAuth, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id FROM users
ORDER BY username
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Metadata,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.DeactivatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id FROM users
WHERE ($3::boolean = FALSE OR deactivated_at IS NULL)
ORDER BY username
LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
	Column3 bool  `json:"column_3"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Metadata,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.DeactivatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users
SET deactivated_at = NULL
WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users
SET is_admin = $2
WHERE id = $1
`

type SetUserAdminParams struct {
	ID      uuid.UUID `json:"id"`
	IsAdmin bool      `json:"is_admin"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.Exec(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2,
    email = $3,
    display_name = $4,
    metadata = $5
WHERE id = $1
RETURNING id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id
`

type UpdateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE users
SET username = $2,
    email = $3,
    display_name = $4,
    is_admin = $5,
    metadata = $6
WHERE id = $1
RETURNING id, username, email, display_name, created_at, modified_at, metadata, password_hash, is_admin, deactivated_at, org_id
`

type UpdateUserAdminParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	IsAdmin     bool        `json:"is_admin"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.IsAdmin,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Metadata,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.OrgID,
	)
	return i, err
}
