// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredAdminSessions = `-- name: CleanupExpiredAdminSessions :exec
DELETE FROM admin_sessions
WHERE expires_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) CleanupExpiredAdminSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredAdminSessions)
	return err
}

const countActiveAdminSessions = `-- name: CountActiveAdminSessions :one
SELECT COUNT(*) FROM admin_sessions
WHERE revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountActiveAdminSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (user_id, token_hash, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, ip_address, user_agent, created_at, expires_at, revoked_at
`

type CreateAdminSessionParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	IpAddress pgtype.Text `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminSessionByToken = `-- name: GetAdminSessionByToken :one
SELECT s.id, s.user_id, s.token_hash, s.ip_address, s.user_agent, s.created_at, s.expires_at, s.revoked_at,
       u.username, u.email, u.is_admin, u.org_id, u.deactivated_at as user_deactivated_at
FROM admin_sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > NOW()
  AND u.deactivated_at IS NULL
`

type GetAdminSessionByTokenRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	IpAddress         pgtype.Text        `json:"ip_address"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	CreatedAt         time.Time          `json:"created_at"`
	ExpiresAt         time.Time          `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	Username          string             `json:"username"`
	Email             pgtype.Text        `json:"email"`
	IsAdmin           bool               `json:"is_admin"`
	OrgID             uuid.UUID          `json:"org_id"`
	UserDeactivatedAt pgtype.Timestamptz `json:"user_deactivated_at"`
}

// Note: Despite the name, this query is used for all user sessions (admin and non-admin)
func (q *Queries) GetAdminSessionByToken(ctx context.Context, tokenHash string) (GetAdminSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByToken, tokenHash)
	var i GetAdminSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.OrgID,
		&i.UserDeactivatedAt,
	)
	return i, err
}

const listActiveAdminSessions = `-- name: ListActiveAdminSessions :many
SELECT s.id, s.user_id, s.token_hash, s.ip_address, s.user_agent, s.created_at, s.expires_at, s.revoked_at,
       u.username
FROM admin_sessions s
JOIN users u ON s.user_id = u.id
WHERE s.revoked_at IS NULL
  AND s.expires_at > NOW()
ORDER BY s.created_at DESC
`

type ListActiveAdminSessionsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	Username  string             `json:"username"`
}

func (q *Queries) ListActiveAdminSessions(ctx context.Context) ([]ListActiveAdminSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdminSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdminSessionsRow{}
	for rows.Next() {
		var i ListActiveAdminSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeAdminSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, id)
	return err
}

const revokeAdminSessionByToken = `-- name: RevokeAdminSessionByToken :exec
UPDATE admin_sessions
SET revoked_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) RevokeAdminSessionByToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeAdminSessionByToken, tokenHash)
	return err
}

const revokeAllAdminSessionsByUser = `-- name: RevokeAllAdminSessionsByUser :exec
UPDATE admin_sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAdminSessionsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAdminSessionsByUser, userID)
	return err
}
