// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git_commits.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGitCommits = `-- name: CountGitCommits :one
SELECT COUNT(*)::int
FROM git_commits
WHERE user_id = $1
`

func (q *Queries) CountGitCommits(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGitCommits, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGitCommit = `-- name: CreateGitCommit :one
INSERT INTO git_commits (
    user_id, commit_hash, commit_message, author_name, author_email, committed_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, guid, user_id, commit_hash, commit_message, author_name, author_email, committed_at, created_at
`

type CreateGitCommitParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	CommitHash    string      `json:"commit_hash"`
	CommitMessage string      `json:"commit_message"`
	AuthorName    pgtype.Text `json:"author_name"`
	AuthorEmail   pgtype.Text `json:"author_email"`
	CommittedAt   time.Time   `json:"committed_at"`
}

func (q *Queries) CreateGitCommit(ctx context.Context, arg CreateGitCommitParams) (GitCommit, error) {
	row := q.db.QueryRow(ctx, createGitCommit,
		arg.UserID,
		arg.CommitHash,
		arg.CommitMessage,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.CommittedAt,
	)
	var i GitCommit
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGitCommit = `-- name: GetGitCommit :one
SELECT id, guid, user_id, commit_hash, commit_message, author_name, author_email, committed_at, created_at FROM git_commits
WHERE guid = $1 AND user_id = $2
`

type GetGitCommitParams struct {
	Guid   uuid.UUID `json:"guid"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetGitCommit(ctx context.Context, arg GetGitCommitParams) (GitCommit, error) {
	row := q.db.QueryRow(ctx, getGitCommit, arg.Guid, arg.UserID)
	var i GitCommit
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGitCommitByHash = `-- name: GetGitCommitByHash :one
SELECT id, guid, user_id, commit_hash, commit_message, author_name, author_email, committed_at, created_at FROM git_commits
WHERE commit_hash = $1 AND user_id = $2
`

type GetGitCommitByHashParams struct {
	CommitHash string    `json:"commit_hash"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetGitCommitByHash(ctx context.Context, arg GetGitCommitByHashParams) (GitCommit, error) {
	row := q.db.QueryRow(ctx, getGitCommitByHash, arg.CommitHash, arg.UserID)
	var i GitCommit
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestGitCommit = `-- name: GetLatestGitCommit :one
SELECT id, guid, user_id, commit_hash, commit_message, author_name, author_email, committed_at, created_at FROM git_commits
WHERE user_id = $1
ORDER BY committed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestGitCommit(ctx context.Context, userID uuid.UUID) (GitCommit, error) {
	row := q.db.QueryRow(ctx, getLatestGitCommit, userID)
	var i GitCommit
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.CommittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGitCommits = `-- name: ListGitCommits :many
SELECT id, guid, user_id, commit_hash, commit_message, author_name, author_email, committed_at, created_at FROM git_commits
WHERE user_id = $1
ORDER BY committed_at DESC
LIMIT $2 OFFSET $3
`

type ListGitCommitsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListGitCommits(ctx context.Context, arg ListGitCommitsParams) ([]GitCommit, error) {
	rows, err := q.db.Query(ctx, listGitCommits, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitCommit{}
	for rows.Next() {
		var i GitCommit
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.CommitHash,
			&i.CommitMessage,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.CommittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitCommitsByDateRange = `-- name: ListGitCommitsByDateRange :many
SELECT id, guid, user_id, commit_hash, commit_message, author_name, author_email, committed_at, created_at FROM git_commits
WHERE user_id = $1
  AND committed_at >= $2
  AND committed_at <= $3
ORDER BY committed_at DESC
`

type ListGitCommitsByDateRangeParams struct {
	UserID        uuid.UUID `json:"user_id"`
	CommittedAt   time.Time `json:"committed_at"`
	CommittedAt_2 time.Time `json:"committed_at_2"`
}

func (q *Queries) ListGitCommitsByDateRange(ctx context.Context, arg ListGitCommitsByDateRangeParams) ([]GitCommit, error) {
	rows, err := q.db.Query(ctx, listGitCommitsByDateRange, arg.UserID, arg.CommittedAt, arg.CommittedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitCommit{}
	for rows.Next() {
		var i GitCommit
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.CommitHash,
			&i.CommitMessage,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.CommittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
