// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countJournalEntriesByType = `-- name: CountJournalEntriesByType :one
SELECT COUNT(*)::int
FROM journal
WHERE user_id = $1 AND entry_type = $2
  AND superseded_by IS NULL
`

type CountJournalEntriesByTypeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	EntryType string    `json:"entry_type"`
}

func (q *Queries) CountJournalEntriesByType(ctx context.Context, arg CountJournalEntriesByTypeParams) (int32, error) {
	row := q.db.QueryRow(ctx, countJournalEntriesByType, arg.UserID, arg.EntryType)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal (
    user_id, entry_type, content, metadata, vector_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at
`

type CreateJournalEntryParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	EntryType string      `json:"entry_type"`
	Content   string      `json:"content"`
	Metadata  []byte      `json:"metadata"`
	VectorID  pgtype.UUID `json:"vector_id"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (Journal, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.UserID,
		arg.EntryType,
		arg.Content,
		arg.Metadata,
		arg.VectorID,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.EntryType,
		&i.Content,
		&i.Metadata,
		&i.VectorID,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM journal
WHERE guid = $1 AND user_id = $2
`

type DeleteJournalEntryParams struct {
	Guid   uuid.UUID `json:"guid"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteJournalEntry(ctx context.Context, arg DeleteJournalEntryParams) error {
	_, err := q.db.Exec(ctx, deleteJournalEntry, arg.Guid, arg.UserID)
	return err
}

const getJournalEntriesByType = `-- name: GetJournalEntriesByType :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE user_id = $1 AND entry_type = $2
  AND superseded_by IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetJournalEntriesByTypeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	EntryType string    `json:"entry_type"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetJournalEntriesByType(ctx context.Context, arg GetJournalEntriesByTypeParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalEntriesByType,
		arg.UserID,
		arg.EntryType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalEntriesByVectorIDs = `-- name: GetJournalEntriesByVectorIDs :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE user_id = $1
  AND vector_id = ANY($2::uuid[])
ORDER BY created_at DESC
`

type GetJournalEntriesByVectorIDsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) GetJournalEntriesByVectorIDs(ctx context.Context, arg GetJournalEntriesByVectorIDsParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getJournalEntriesByVectorIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE guid = $1 AND user_id = $2
`

type GetJournalEntryParams struct {
	Guid   uuid.UUID `json:"guid"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, arg.Guid, arg.UserID)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.EntryType,
		&i.Content,
		&i.Metadata,
		&i.VectorID,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getJournalEntryByID = `-- name: GetJournalEntryByID :one
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE id = $1 AND user_id = $2
`

type GetJournalEntryByIDParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetJournalEntryByID(ctx context.Context, arg GetJournalEntryByIDParams) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByID, arg.ID, arg.UserID)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.EntryType,
		&i.Content,
		&i.Metadata,
		&i.VectorID,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getRecentDecisions = `-- name: GetRecentDecisions :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE user_id = $1
  AND entry_type = 'decision'
  AND superseded_by IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentDecisionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetRecentDecisions(ctx context.Context, arg GetRecentDecisionsParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getRecentDecisions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSolutions = `-- name: GetRecentSolutions :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE user_id = $1
  AND entry_type = 'solution'
  AND superseded_by IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentSolutionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetRecentSolutions(ctx context.Context, arg GetRecentSolutionsParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getRecentSolutions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE user_id = $1
  AND ($2::varchar IS NULL OR entry_type = $2)
  AND superseded_by IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListJournalEntriesParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listJournalEntries,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByDateRange = `-- name: ListJournalEntriesByDateRange :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at FROM journal
WHERE user_id = $1
  AND created_at >= $2
  AND created_at <= $3
  AND ($4::varchar IS NULL OR entry_type = $4)
  AND superseded_by IS NULL
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListJournalEntriesByDateRangeParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Column4     string    `json:"column_4"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListJournalEntriesByDateRange(ctx context.Context, arg ListJournalEntriesByDateRangeParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByDateRange,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJournalFullText = `-- name: SearchJournalFullText :many
SELECT id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at,
    ts_rank(to_tsvector('english', content), plainto_tsquery('english', $2)) as rank
FROM journal
WHERE user_id = $1
  AND to_tsvector('english', content) @@ plainto_tsquery('english', $2)
  AND superseded_by IS NULL
ORDER BY rank DESC, created_at DESC
LIMIT $3
`

type SearchJournalFullTextParams struct {
	UserID         uuid.UUID `json:"user_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

type SearchJournalFullTextRow struct {
	ID           int64       `json:"id"`
	Guid         uuid.UUID   `json:"guid"`
	UserID       uuid.UUID   `json:"user_id"`
	EntryType    string      `json:"entry_type"`
	Content      string      `json:"content"`
	Metadata     []byte      `json:"metadata"`
	VectorID     pgtype.UUID `json:"vector_id"`
	SupersededBy pgtype.UUID `json:"superseded_by"`
	CreatedAt    time.Time   `json:"created_at"`
	ModifiedAt   time.Time   `json:"modified_at"`
	Rank         float32     `json:"rank"`
}

func (q *Queries) SearchJournalFullText(ctx context.Context, arg SearchJournalFullTextParams) ([]SearchJournalFullTextRow, error) {
	rows, err := q.db.Query(ctx, searchJournalFullText, arg.UserID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchJournalFullTextRow{}
	for rows.Next() {
		var i SearchJournalFullTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.UserID,
			&i.EntryType,
			&i.Content,
			&i.Metadata,
			&i.VectorID,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJournalVectorID = `-- name: SetJournalVectorID :exec
UPDATE journal
SET vector_id = $3
WHERE guid = $1 AND user_id = $2
`

type SetJournalVectorIDParams struct {
	Guid     uuid.UUID   `json:"guid"`
	UserID   uuid.UUID   `json:"user_id"`
	VectorID pgtype.UUID `json:"vector_id"`
}

func (q *Queries) SetJournalVectorID(ctx context.Context, arg SetJournalVectorIDParams) error {
	_, err := q.db.Exec(ctx, setJournalVectorID, arg.Guid, arg.UserID, arg.VectorID)
	return err
}

const supersedeJournalEntry = `-- name: SupersedeJournalEntry :exec
UPDATE journal
SET superseded_by = $3
WHERE guid = $1 AND user_id = $2
`

type SupersedeJournalEntryParams struct {
	Guid         uuid.UUID   `json:"guid"`
	UserID       uuid.UUID   `json:"user_id"`
	SupersededBy pgtype.UUID `json:"superseded_by"`
}

func (q *Queries) SupersedeJournalEntry(ctx context.Context, arg SupersedeJournalEntryParams) error {
	_, err := q.db.Exec(ctx, supersedeJournalEntry, arg.Guid, arg.UserID, arg.SupersededBy)
	return err
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal
SET content = $3,
    metadata = $4
WHERE guid = $1 AND user_id = $2
RETURNING id, guid, user_id, entry_type, content, metadata, vector_id, superseded_by, created_at, modified_at
`

type UpdateJournalEntryParams struct {
	Guid     uuid.UUID `json:"guid"`
	UserID   uuid.UUID `json:"user_id"`
	Content  string    `json:"content"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (Journal, error) {
	row := q.db.QueryRow(ctx, updateJournalEntry,
		arg.Guid,
		arg.UserID,
		arg.Content,
		arg.Metadata,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.UserID,
		&i.EntryType,
		&i.Content,
		&i.Metadata,
		&i.VectorID,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
